services:
  - type: web
    name: electricity-consumption-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
